# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Shopify Wishlist App"
client_id = "replace-with-your-client-id"
application_url = "replace-with-your-app-url"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "replace-with-your-redirect-url/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[[extensions]]
type = "theme"
name = "wishlist-extension"
handle = "wishlist-extension"

[[extensions]]
type = "web_pixel"
name = "wishlist-pixel"
handle = "wishlist-pixel"